services:
  db:
    image: postgres:16
    # docker_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/T2_database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      UPLOAD_FOLDER: ${UPLOAD_FOLDER}
    volumes:
      - ./upload_2cam:/app/upload_2cam
    ports:
      - "6601:5000"

  frontend:
    build:
      context: ./urban_dash
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "6602:4173"
    environment:
      VITE_API_URL: ${VITE_API_URL}

volumes:
  db_data:
